apiVersion: v1
kind: Pod
metadata:
  name: configmap-options-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.19.9
      env:
        # Define the environment variable
        - name: VAR5
          valueFrom:
            configMapKeyRef:
              name: options             # The ConfigMap this value comes from.
              key: var5                 # The key to fetch.
