apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
spec:
  containers:
  - name: busybox-1
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo hello1; sleep 3600"]
  - name: busybox-2
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo hello2; sleep 3600"]
  restartPolicy: Never
