apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "200m"
          memory: "512Mi"
        requests:
          cpu: "100m"
          memory: "256Mi"
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
