apiVersion: v1
kind: Pod
metadata:
  name: echo-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: echo-demo-container
    image: busybox
    command: ["echo"]
    args: ["HELLO, K8S!"]
  restartPolicy: Never
