apiVersion: v1
kind: Pod
metadata:
  name: http-request
  labels:
    role: my-role
spec:
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /
          port: 8080
          httpHeaders:
          - name: Custom-Header
            value: Awesome
        initialDelaySeconds: 3
        periodSeconds: 3
