apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  USERNAME: my-username
  PASSWORD: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: PASSWORD
      - name: SECRET_USERNAME
        valeFrom:
          secretKeyRef:
            name: mysecret
            key: USERNAME
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-nginx-pod
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret
  containers:
    - name: web-application
      image: nginx
      volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: "/etc/foo"
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
